import {
  CategoryResponse,
  ProductSummaryResponse,
  ProductVariantDetailResponse,
  WarehouseResponse,
  OrderResponse,
  ShipmentResponse,
  AddressResponse,
  NotificationResponse,
  InventoryResponse,
} from '../types';

export const MOCK_CATEGORIES: CategoryResponse[] = [
  {
    id: 'cat-01',
    name: 'Laptop & Máy Tính',
    description: 'Máy tính xách tay cao cấp, mỏng nhẹ và gaming hiệu năng đỉnh cao',
    slug: 'laptop',
    icon: 'Laptop',
  },
  {
    id: 'cat-02',
    name: 'Điện Thoại & Tablet',
    description: 'Flagship smartphone, máy tính bảng hàng đầu thị trường',
    slug: 'smartphones',
    icon: 'Smartphone',
  },
  {
    id: 'cat-03',
    name: 'Âm Thanh & Tai Nghe',
    description: 'Tai nghe chống ồn chủ động, loa bluetooth không dây trung thực',
    slug: 'audio',
    icon: 'Headphones',
  },
  {
    id: 'cat-04',
    name: 'Phụ Kiện & Gaming Gear',
    description: 'Bàn phím cơ, chuột công thái học, sạc nhanh GaN cao cấp',
    slug: 'accessories',
    icon: 'Keyboard',
  },
  {
    id: 'cat-05',
    name: 'Smart Home & Gia Dụng',
    description: 'Robot hút bụi, đèn thông minh, máy lọc không khí hiện đại',
    slug: 'smart-home',
    icon: 'Home',
  },
];

export const MOCK_WAREHOUSES: WarehouseResponse[] = [
  {
    id: 'wh-01',
    code: 'WH-HN-01',
    name: 'Tổng Kho Hà Nội (Long Biên)',
    addressLine: 'Số 15 KCN Đài Tư, Quận Long Biên, TP. Hà Nội',
    latitude: 21.0372,
    longitude: 105.8924,
    active: true,
  },
  {
    id: 'wh-02',
    code: 'WH-HCM-01',
    name: 'Tổng Kho TP. Hồ Chí Minh (Tân Bình)',
    addressLine: 'Số 45 Đường Trường Sơn, Phường 2, Quận Tân Bình, TP. HCM',
    latitude: 10.8015,
    longitude: 106.6578,
    active: true,
  },
  {
    id: 'wh-03',
    code: 'WH-DN-01',
    name: 'Kho Vận Trung Chuyển Đà Nẵng (Hải Châu)',
    addressLine: 'Số 128 Đường 2 Tháng 9, Quận Hải Châu, TP. Đà Nẵng',
    latitude: 16.0544,
    longitude: 108.2022,
    active: true,
  },
];

export const MOCK_PRODUCTS: ProductSummaryResponse[] = [
  {
    id: 'prod-01',
    name: 'MacBook Pro 14" M3 Pro (18GB / 512GB SSD)',
    categoryId: 'cat-01',
    categoryName: 'Laptop & Máy Tính',
    active: true,
    variantId: 'var-01-spaceblack',
    sku: 'MBP-14-M3P-BLK',
    variantName: 'Space Black / 18GB / 512GB',
    price: 49990000,
    availableQuantity: 38,
    reservedQuantity: 4,
    imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviewCount: 128,
    badge: 'Bán chạy nhất',
  },
  {
    id: 'prod-02',
    name: 'iPhone 16 Pro Max 256GB Titan Tự Nhiên',
    categoryId: 'cat-02',
    categoryName: 'Điện Thoại & Tablet',
    active: true,
    variantId: 'var-02-desert',
    sku: 'IP16PM-256-DESERT',
    variantName: 'Titan Sa Mạc / 256GB',
    price: 34490000,
    availableQuantity: 65,
    reservedQuantity: 12,
    imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=800&q=80',
    rating: 4.95,
    reviewCount: 310,
    badge: 'Mới ra mắt',
  },
  {
    id: 'prod-03',
    name: 'Tai Nghe Sony WH-1000XM5 Chống Ồn Flagship',
    categoryId: 'cat-03',
    categoryName: 'Âm Thanh & Tai Nghe',
    active: true,
    variantId: 'var-03-silver',
    sku: 'SONY-XM5-SLV',
    variantName: 'Bạc Ánh Kim / Hi-Res Audio',
    price: 7990000,
    availableQuantity: 42,
    reservedQuantity: 2,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    reviewCount: 94,
    badge: 'Top Âm Thanh',
  },
  {
    id: 'prod-04',
    name: 'Apple Watch Ultra 2 GPS + Cellular 49mm Titanium',
    categoryId: 'cat-04',
    categoryName: 'Phụ Kiện & Gaming Gear',
    active: true,
    variantId: 'var-04-ocean',
    sku: 'AWU2-49-OCEAN',
    variantName: 'Vỏ Titan / Dây Ocean Xanh Đậm',
    price: 21490000,
    availableQuantity: 19,
    reservedQuantity: 3,
    imageUrl: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80',
    rating: 4.85,
    reviewCount: 76,
    badge: 'Đẳng cấp Thể thao',
  },
  {
    id: 'prod-05',
    name: 'Bàn Phím Cơ Custom Không Dây Keychron Q1 Pro',
    categoryId: 'cat-04',
    categoryName: 'Phụ Kiện & Gaming Gear',
    active: true,
    variantId: 'var-05-redsw',
    sku: 'KEY-Q1P-RED',
    variantName: 'Khung Nhôm CNC / Red Switch / RGB',
    price: 4690000,
    availableQuantity: 24,
    reservedQuantity: 1,
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
    rating: 4.75,
    reviewCount: 52,
    badge: 'Khuyên dùng',
  },
  {
    id: 'prod-06',
    name: 'Dell XPS 16 9640 Core Ultra 7 OLED 4K Touch',
    categoryId: 'cat-01',
    categoryName: 'Laptop & Máy Tính',
    active: true,
    variantId: 'var-06-oled',
    sku: 'DELL-XPS16-OLED',
    variantName: 'Bạc Graphite / 32GB / 1TB SSD',
    price: 58900000,
    availableQuantity: 14,
    reservedQuantity: 0,
    imageUrl: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    reviewCount: 40,
    badge: 'Đồ họa Chuyên nghiệp',
  },
  {
    id: 'prod-07',
    name: 'Loa Không Dây Marshall Stanmore III Vintage',
    categoryId: 'cat-03',
    categoryName: 'Âm Thanh & Tai Nghe',
    active: true,
    variantId: 'var-07-black',
    sku: 'MARSHALL-ST3-BLK',
    variantName: 'Màu Đen Cổ Điển / Bluetooth 5.2',
    price: 9490000,
    availableQuantity: 28,
    reservedQuantity: 2,
    imageUrl: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviewCount: 115,
    badge: 'Hot trend',
  },
  {
    id: 'prod-08',
    name: 'Robot Hút Bụi Lau Nhà Ecovacs Deebot T30 Pro Omni',
    categoryId: 'cat-05',
    categoryName: 'Smart Home & Gia Dụng',
    active: true,
    variantId: 'var-08-omni',
    sku: 'ECO-T30-OMNI',
    variantName: 'Trạm Giặt Nước Nóng Tự Động / 11000Pa',
    price: 16990000,
    availableQuantity: 16,
    reservedQuantity: 2,
    imageUrl: 'https://images.unsplash.com/photo-1518640467707-6811f4a6ab73?auto=format&fit=crop&w=800&q=80',
    rating: 4.88,
    reviewCount: 88,
    badge: 'Công nghệ 2026',
  },
];

export const MOCK_PRODUCT_DETAILS: Record<string, ProductVariantDetailResponse[]> = {
  'prod-01': [
    {
      productId: 'prod-01',
      productName: 'MacBook Pro 14" M3 Pro (18GB / 512GB SSD)',
      variantId: 'var-01-spaceblack',
      sku: 'MBP-14-M3P-BLK',
      variantName: 'Đen Không Gian (Space Black) / 512GB',
      price: 49990000,
      availableQuantity: 25,
      reservedQuantity: 3,
      imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
      description: 'Chip Apple M3 Pro với CPU 11 lõi và GPU 14 lõi, màn hình Liquid Retina XDR 120Hz siêu sáng, thời lượng pin lên đến 18 giờ liên tục.',
      attributes: { 'Màu sắc': 'Space Black', 'RAM': '18GB Unified Memory', 'Ổ cứng': '512GB NVMe SSD' },
    },
    {
      productId: 'prod-01',
      productName: 'MacBook Pro 14" M3 Pro (36GB / 1TB SSD)',
      variantId: 'var-01-silver-1tb',
      sku: 'MBP-14-M3P-SLV1T',
      variantName: 'Bạc Ánh Kim (Silver) / 1TB SSD',
      price: 59990000,
      availableQuantity: 13,
      reservedQuantity: 1,
      imageUrl: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=800&q=80',
      description: 'Phiên bản cấu hình cao cấp với 36GB RAM tối ưu cho lập trình viên, thiết kế 3D và dựng phim chuyên nghiệp.',
      attributes: { 'Màu sắc': 'Silver', 'RAM': '36GB Unified Memory', 'Ổ cứng': '1TB NVMe SSD' },
    },
  ],
  'prod-02': [
    {
      productId: 'prod-02',
      productName: 'iPhone 16 Pro Max 256GB Titan Tự Nhiên',
      variantId: 'var-02-desert',
      sku: 'IP16PM-256-DESERT',
      variantName: 'Titan Sa Mạc / 256GB',
      price: 34490000,
      availableQuantity: 35,
      reservedQuantity: 8,
      imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=800&q=80',
      description: 'Khung viền titan siêu nhẹ cấp hàng không vũ trụ, chip A18 Pro với trí tuệ nhân tạo Apple Intelligence, nút Camera Control thế hệ mới.',
      attributes: { 'Màu sắc': 'Titan Sa Mạc', 'Dung lượng': '256GB', 'Màn hình': '6.9 inch Super Retina XDR' },
    },
    {
      productId: 'prod-02',
      productName: 'iPhone 16 Pro Max 512GB Titan Đen',
      variantId: 'var-02-black-512',
      sku: 'IP16PM-512-BLK',
      variantName: 'Titan Đen / 512GB',
      price: 39990000,
      availableQuantity: 30,
      reservedQuantity: 4,
      imageUrl: 'https://images.unsplash.com/photo-1591337676887-a217a6970a8a?auto=format&fit=crop&w=800&q=80',
      description: 'Màu Titan Đen bí ẩn, không gian lưu trữ 512GB thoải mái quay video 4K ProRes 120fps.',
      attributes: { 'Màu sắc': 'Titan Đen', 'Dung lượng': '512GB', 'Màn hình': '6.9 inch Super Retina XDR' },
    },
  ],
};

export const MOCK_ADDRESSES: AddressResponse[] = [
  {
    id: 'addr-01',
    recipientName: 'Nguyễn Văn An',
    phone: '0988 123 456',
    addressLine: 'Toà nhà Keangnam Landmark 72, Đường Phạm Hùng',
    city: 'Hà Nội',
    latitude: 21.0173,
    longitude: 105.7838,
    defaultAddress: true,
  },
  {
    id: 'addr-02',
    recipientName: 'Nguyễn Văn An',
    phone: '0988 123 456',
    addressLine: 'Tầng 18 Vincom Center, 72 Lê Thánh Tôn, Bến Nghé, Quận 1',
    city: 'TP. Hồ Chí Minh',
    latitude: 10.7778,
    longitude: 106.7020,
    defaultAddress: false,
  },
];

export const MOCK_ORDERS: OrderResponse[] = [
  {
    id: 'ord-88910',
    orderNumber: 'ORD-2026-9810',
    status: 'CONFIRMED',
    totalAmount: 42480000,
    city: 'Hà Nội',
    recipientName: 'Nguyễn Văn An',
    phone: '0988 123 456',
    addressLine: 'Toà nhà Keangnam Landmark 72, Đường Phạm Hùng, Hà Nội',
    createdAt: '2026-09-17T14:30:00Z',
    items: [
      {
        id: 'ord-item-01',
        variantId: 'var-02-desert',
        productName: 'iPhone 16 Pro Max 256GB Titan Tự Nhiên',
        variantName: 'Titan Sa Mạc / 256GB',
        sku: 'IP16PM-256-DESERT',
        price: 34490000,
        quantity: 1,
        subtotal: 34490000,
        imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'ord-item-02',
        variantId: 'var-03-silver',
        productName: 'Tai Nghe Sony WH-1000XM5 Chống Ồn Flagship',
        variantName: 'Bạc Ánh Kim / Hi-Res Audio',
        sku: 'SONY-XM5-SLV',
        price: 7990000,
        quantity: 1,
        subtotal: 7990000,
        imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      },
    ],
  },
  {
    id: 'ord-88909',
    orderNumber: 'ORD-2026-9809',
    status: 'DELIVERED',
    totalAmount: 49990000,
    city: 'Hà Nội',
    recipientName: 'Nguyễn Văn An',
    phone: '0988 123 456',
    addressLine: 'Toà nhà Keangnam Landmark 72, Đường Phạm Hùng, Hà Nội',
    createdAt: '2026-09-14T09:15:00Z',
    items: [
      {
        id: 'ord-item-03',
        variantId: 'var-01-spaceblack',
        productName: 'MacBook Pro 14" M3 Pro (18GB / 512GB SSD)',
        variantName: 'Space Black / 18GB / 512GB',
        sku: 'MBP-14-M3P-BLK',
        price: 49990000,
        quantity: 1,
        subtotal: 49990000,
        imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
      },
    ],
  },
];

export const MOCK_SHIPMENTS: ShipmentResponse[] = [
  {
    id: 'shp-01',
    orderId: 'ord-88910',
    orderNumber: 'ORD-2026-9810',
    warehouseId: 'wh-01',
    warehouseName: 'Tổng Kho Hà Nội (Long Biên)',
    shipperId: 's3030303-0000-0000-0000-000000000003',
    shipperName: 'Trần Văn Tốc Độ (0912 345 678)',
    status: 'OUT_FOR_DELIVERY',
    trackingNumber: 'VNPOST-HN-883921',
    recipientName: 'Nguyễn Văn An',
    recipientPhone: '0988 123 456',
    deliveryAddress: 'Toà nhà Keangnam Landmark 72, Đường Phạm Hùng, Hà Nội',
    distanceKm: 8.4,
    updatedAt: '2026-09-18T00:15:00Z',
    timeline: [
      {
        status: 'PENDING_PACKING',
        timestamp: '2026-09-17T15:00:00Z',
        location: 'Tổng Kho Hà Nội (Long Biên)',
        note: 'Đơn hàng được tiếp nhận và đóng gói theo chuẩn niêm phong an toàn.',
      },
      {
        status: 'READY_FOR_PICKUP',
        timestamp: '2026-09-17T17:30:00Z',
        location: 'Khu vực bốc dỡ Cảng Kho Long Biên',
        note: 'Kiện hàng sẵn sàng bàn giao cho đội ngũ vận chuyển.',
      },
      {
        status: 'PICKED_UP',
        timestamp: '2026-09-17T19:00:00Z',
        location: 'Bưu cục trung chuyển Cầu Giấy',
        note: 'Shipper Trần Văn Tốc Độ đã nhận kiện hàng.',
      },
      {
        status: 'IN_TRANSIT',
        timestamp: '2026-09-17T22:30:00Z',
        location: 'Bưu cục trung chuyển Cầu Giấy',
        note: 'Đang điều phối phân luồng tuyến giao Nam Từ Liêm.',
      },
      {
        status: 'OUT_FOR_DELIVERY',
        timestamp: '2026-09-18T00:15:00Z',
        location: 'Tuyến đường Phạm Hùng',
        note: 'Shipper đang trên đường giao đến bạn. Dự kiến giao trong 30-45 phút.',
      },
    ],
  },
];

export const MOCK_NOTIFICATIONS: NotificationResponse[] = [
  {
    id: 'notif-01',
    title: 'Đơn hàng đang trên đường giao!',
    message: 'Kiện hàng mã VNPOST-HN-883921 đang được giao đến Landmark 72. Vui lòng để ý điện thoại.',
    status: 'SENT',
    read: false,
    createdAt: '2026-09-18T00:15:00Z',
  },
  {
    id: 'notif-02',
    title: 'Đặt hàng thành công #ORD-2026-9810',
    message: 'Cảm ơn bạn đã mua hàng! Hệ thống đã điều phối giữ hàng an toàn tại Tổng Kho Long Biên.',
    status: 'SENT',
    read: true,
    createdAt: '2026-09-17T14:30:00Z',
  },
  {
    id: 'notif-03',
    title: 'Ưu đãi Flash Sale mùa Thu 2026',
    message: 'Giảm đến 15% cho dòng sản phẩm Laptop và Gaming Gear hôm nay.',
    status: 'SENT',
    read: true,
    createdAt: '2026-09-16T08:00:00Z',
  },
];

export const MOCK_INVENTORY: InventoryResponse[] = [
  {
    id: 'inv-01',
    warehouseId: 'wh-01',
    warehouseName: 'Tổng Kho Hà Nội (Long Biên)',
    variantId: 'var-01-spaceblack',
    sku: 'MBP-14-M3P-BLK',
    productName: 'MacBook Pro 14" M3 Pro',
    availableQuantity: 25,
    reservedQuantity: 3,
  },
  {
    id: 'inv-02',
    warehouseId: 'wh-02',
    warehouseName: 'Tổng Kho TP. Hồ Chí Minh (Tân Bình)',
    variantId: 'var-01-spaceblack',
    sku: 'MBP-14-M3P-BLK',
    productName: 'MacBook Pro 14" M3 Pro',
    availableQuantity: 13,
    reservedQuantity: 1,
  },
  {
    id: 'inv-03',
    warehouseId: 'wh-01',
    warehouseName: 'Tổng Kho Hà Nội (Long Biên)',
    variantId: 'var-02-desert',
    sku: 'IP16PM-256-DESERT',
    productName: 'iPhone 16 Pro Max 256GB',
    availableQuantity: 35,
    reservedQuantity: 8,
  },
  {
    id: 'inv-04',
    warehouseId: 'wh-02',
    warehouseName: 'Tổng Kho TP. Hồ Chí Minh (Tân Bình)',
    variantId: 'var-02-desert',
    sku: 'IP16PM-256-DESERT',
    productName: 'iPhone 16 Pro Max 256GB',
    availableQuantity: 30,
    reservedQuantity: 4,
  },
  {
    id: 'inv-05',
    warehouseId: 'wh-03',
    warehouseName: 'Kho Vận Trung Chuyển Đà Nẵng',
    variantId: 'var-03-silver',
    sku: 'SONY-XM5-SLV',
    productName: 'Tai Nghe Sony WH-1000XM5',
    availableQuantity: 20,
    reservedQuantity: 1,
  },
];
